---
title: "R Leslie Matrix Example"
author: "Joe DeCesaro"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating Matrices in R

Use the `matrix()` function to wrap a seires of values (a vector) into a matrix

- Use `nrow = ` to specify number of rows
- Use `ncol = ` to specify number of columns
- Use `byrow = True` to populate the matrix by rows instead of columns

```{r}
cats <- c(1, 3, 6, 5, 10, 4, 0.2, 15)

# wrap cats into a matrix

cat_matrix <- matrix(data = cats, nrow = 4, ncol = 5, byrow = TRUE)
```

```{r}
dogs <- matrix(data = c(1, 0, 2, 3), nrow = 2, ncol = 2, byrow = TRUE)

# you can put the vector striaght into a matrix

lizards <- matrix(data = c(2, 6, 7, 3), nrow = 2, ncol = 2, byrow = TRUE)

birds <- matrix(data = c(4, 8, 9, 11), nrow = 2, ncol = 2, byrow = TRUE)

dogs + lizards

4 * birds

# Use the dot product operator for matrix mulitiplication

dogs %*% lizards
```

## Making a Leslie Matrix
```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), nrow = 3, ncol = 3, byrow = TRUE)

# Specify the initial conditions
# What is the population in each life stage at year 0?

insect_y0 <- c(12000, 700, 500)

# Project the population in each life stage for year 1
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Project the population at wach life stage for years 2, 3, and 4

insect_y2 <- insect_leslie %*% insect_y1
insect_y3 <- insect_leslie %*% insect_y2
insect_y4 <- insect_leslie %*% insect_y3

insect_y2
insect_y3
insect_y4

```

## Making a Leslie Matrix with a 60% survival rate for adult females
```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0.6), nrow = 3, ncol = 3, byrow = TRUE)

# Add 0.6 in the last data point in the matrix

insect_y0 <- c(12000, 700, 500)

# Project the population in each life stage for year 1
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Project the population at wach life stage for years 2, 3, and 4

insect_y2 <- insect_leslie %*% insect_y1
insect_y3 <- insect_leslie %*% insect_y2
insect_y4 <- insect_leslie %*% insect_y3

insect_y2
insect_y3
insect_y4

```


